apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
    service: backend
spec:
  ports:
    - name: client
      port: 8001
      protocol: TCP
      targetPort: 8001
  selector:
    app: backend
    service: backend
  type: ClusterIP