apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
    service: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      service: frontend
  template:
    metadata:
      name: frontend
      labels:
        app: frontend
        service: frontend
    spec:
      containers:
        - name: frontend
          image: stakaterfrontend:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: frontend-service-config-volume
              mountPath: /config/
      volumes:
        - name: frontend-service-config-volume
          configMap:
            name: frontend-service-config
      restartPolicy: Always